import existingOrders from '../fixtures/existingOrders.json';
import postResponse from '../fixtures/postResponse.json';

describe('empty spec', () => {
  beforeEach(() => {
    cy.intercept("http://localhost:3001/api/v1/orders", existingOrders)
    .visit(
      "http://localhost:3000/?name=&sofritas="
    );
  });

  it("Should display existing orders", () => {
    cy.get("#1")
      .children("h3")
      .should("contain", "Pat")
      .get("#1")
      .children("ul")
      .should("have.class", "ingredient-list")
      .children(0)
      .should("contain", "beans")
      .get("#1")
      .children("ul")
      .children(1)
      .should("contain", "lettuce")
      .get("#1")
      .children("ul")
      .children(2)
      .should("contain", "carnitas")
      .get("#1")
      .children("ul")
      .children(3)
      .should("contain", "queso fresco")
      .get("#1")
      .children("ul")
      .children(4)
      .should("contain", "jalapeno");

    cy.get("#2")
      .children("h3")
      .should("contain", "Sam")
      .get("#2")
      .children("ul")
      .should("have.class", "ingredient-list")
      .children(0)
      .should("contain", "steak")
      .get("#2")
      .children("ul")
      .children(1)
      .should("contain", "pico de gallo")
      .get("#2")
      .children("ul")
      .children(2)
      .should("contain", "lettuce")
      .get("#2")
      .children("ul")
      .children(3)
      .should("contain", "carnitas")
      .get("#2")
      .children("ul")
      .children(4)
      .should("contain", "queso fresco")
      .get("#2")
      .children("ul")
      .children(4)
      .should("contain", "queso fresco")
      .get('#2')
      .children("ul")
      .children(5)
      .should("contain", "jalapeno")
  });

  it('Should display a new order after making one', () => {
    cy.intercept("POST", "http://localhost:3001/api/v1/orders", postResponse)
      .get('input[placeholder="Name"]')
      .type("Alex")
      .get('button[name="sofritas"]')
      .click()
      .get('button[name="beans"]')
      .click()
      .get('button[name="sour cream"]')
      .click()
      .get('button[name="carnitas"]')
      .click()
      .get('button[name="queso fresco"]')
      .click()
      .get("button")
      .contains("Submit Order")
      .click()
      .get("#3")
      .children("h3")
      .should("contain", "Alex")
      .get("#3")
      .children("ul")
      .should("have.class", "ingredient-list")
      .children(0)
      .should("contain", "sofritas")
      .get("#3")
      .children("ul")
      .children(1)
      .should("contain", "beans")
      .get("#3")
      .children("ul")
      .children(2)
      .should("contain", "sour cream")
      .get("#3")
      .children("ul")
      .children(3)
      .should("contain", "carnitas")
      .get("#3")
      .children("ul")
      .children(4)
      .should("contain", "queso fresco")
  });
})